name: "Workflow Sample"

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/2 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install Node"
        uses: actions/setup-node@v1
      - name: 'Run Code'
        run : node index.js